name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Upgrade NPM
        run: npm install -g npm@8.19.4
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build
        run: npm build